# arduino
cooldown_stream_reader: None
selected_listen_com_port: None

# log
log_directory_storage: C:\Users\slava\Documents\House Flipper\Profiles.backup\Profile 1\Backup-2025-07-03 23.43\CatchedTextures_BeforeSummary.dat
data_directory_storage: C:\Users\slava\Downloads

# dota type
data_view_type: C|percent
